# Generated by Django 5.1.3 on 2025-10-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bid_bid_amount_alter_bid_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='timsestamp',
            new_name='timestamp',
        ),
    ]
