# Generated by Django 5.1.3 on 2024-12-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_category_description_delete_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
