# Generated by Django 5.1.3 on 2025-10-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_sold',
        ),
    ]
