# Generated by Django 5.1.3 on 2024-12-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_delete_bid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
