# Generated by Django 5.1.3 on 2025-01-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_category_listing_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
