# Generated by Django 5.1.3 on 2025-01-15 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_category_listing_category_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='publication_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='publication_user',
        ),
        migrations.AddField(
            model_name='listing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
