# Generated by Django 5.1.3 on 2025-02-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchlist',
        ),
    ]
