# Generated by Django 5.1.3 on 2025-04-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
